# Generated by Django 6.0 on 2025-12-28 12:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition Basics'), ('meals', 'Meal Planning'), ('healthy', 'Healthy Habits'), ('recipes', 'Recipes'), ('fitness', 'Fitness & Nutrition')], default='nutrition', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbs (g)')),
                ('protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Protein (g)')),
                ('fat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fat (g)')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_protein_goal', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_carbs_goal', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_fat_goal', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
